<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Lead extends Model
{
    use SoftDeletes;

    protected $table = 'leads';

    protected $keyType = 'string';
    public $incrementing = false;

    const UPDATED_AT = null;

    protected $fillable = [
        'id',
        'name',
        'email',
        'phone',
        'source',
        'status',
        'stage',
        'approved_at',
        'welcome_email_sent_at',
        'survey_email_sent_at',
        'survey_requested_at',
        'survey_booked_at',
        'quotation_sent_at',
        'quotation_status',
        'quotation_approved_at',
        'invoice_issued_at',
        'reminder_1_scheduled_at',
        'reminder_2_scheduled_at',
        'reminder_1_sent_at',
        'reminder_2_sent_at',
        'reminder_stage',
        'reminder_next_at',
        'reminder_context',
        'last_response_at',
        'survey_requested_date',
        'survey_requested_time_range',
        'survey_notes',
        'reschedule_proposed_date',
        'reschedule_proposed_time',
        'reschedule_status',
        'reschedule_token',
        'survey_status',
        'survey_type',
        'survey_approved_at',
        'app_user_password',
        'credentials_sent_at',
        'video_call_room_id',
        'video_call_status',
        'video_call_token',
        'video_call_caller_id',
        'video_call_caller_name',
        'video_call_caller_role',
        'video_call_is_video',
        'video_call_started_at',
        'video_call_ended_at',
        'surveyor_name',
        'surveyor_email',
        'surveyor_report_notes',
        'surveyor_media',
        'surveyor_completed_at',
        'driver_id',
        'driver_name',
        'driver_email',
        'driver_phone',
        'driver_assigned_at',
        'move_type',
        'lead_type',
        'from_location',
        'to_location',
        'move_date',
        'est_value',
        'ai_score',
        'priority',
        'indicative_quote_range',
        'scope_summary',
        'missing_information_summary',
        'special_item_prompt',
        'survey_deadline',
        'recommended_survey_type',
        'quoted_services',
        'quote_valid_until',
        'deposit_amount_or_percent',
        'deposit_instruction',
        'quote_version',
        'arrival_window',
        'job_lead_name',
        'payment_status',
        'initial_deposit_paid',
        'total_deposit_paid',
        'coordinator_name',
        'completion_date',
        'review_platform_name',
        'review_date',
        'referral_code',
        'referral_offer',
        // ── Flutter Survey Report Structured Fields (Section C–G) ──
        'property_type',
        'cargo_volume',
        'total_boxes',
        'recommended_vehicle',
        'packing_service',
        'access_origin',
        'lift_available',
        'parking_available',
        'custom_access_fields',
        'requires_disassembly',
        'beds_quantity',
        'wardrobes_quantity',
        'custom_dismantle_items',
        'has_fragile_items',
        'fine_art_paintings',
        'piano_antique_items',
        'custom_fragile_fields',
        'special_instructions',
        'surveyor_findings',
        'client_job_status',
        'driver_job_status',
        'job_reschedule_reason',
        'job_proposed_date',
        'job_proposed_time',
        'job_schedule_token',
        'job_started_at',
        'job_completed_at',
        'selfie_url',
        'start_meter_url',
        'start_back_url',
        'start_odometer',
        'end_meter_url',
        'end_back_url',
        'end_odometer',
        'distance_km',
        'fuel_liters',
    ];

    protected $casts = [
        'est_value'               => 'decimal:2',
        'initial_deposit_paid'    => 'boolean',
        'total_deposit_paid'      => 'decimal:2',
        'ai_score'                => 'integer',
        'reminder_stage'          => 'integer',
        'move_date'               => 'date',
        'approved_at'             => 'datetime',
        'welcome_email_sent_at'   => 'datetime',
        'survey_email_sent_at'    => 'datetime',
        'survey_requested_at'     => 'datetime',
        'survey_booked_at'        => 'datetime',
        'survey_approved_at'      => 'datetime',
        'surveyor_completed_at'   => 'datetime',
        'quotation_sent_at'       => 'datetime',
        'quotation_approved_at'   => 'datetime',
        'invoice_issued_at'       => 'datetime',
        'reminder_1_scheduled_at' => 'datetime',
        'reminder_2_scheduled_at' => 'datetime',
        'reminder_1_sent_at'      => 'datetime',
        'reminder_2_sent_at'      => 'datetime',
        'reminder_next_at'        => 'datetime',
        'last_response_at'        => 'datetime',
        'credentials_sent_at'     => 'datetime',
        'video_call_started_at'   => 'datetime',
        'video_call_ended_at'     => 'datetime',
        'driver_assigned_at'      => 'datetime',
        'job_started_at'          => 'datetime',
        'job_completed_at'        => 'datetime',
        'job_proposed_date'       => 'date',
        'start_odometer'          => 'float',
        'end_odometer'            => 'float',
        'distance_km'             => 'float',
        'fuel_liters'             => 'float',
        'created_at'              => 'datetime',
        'lift_available'          => 'boolean',
        'parking_available'       => 'boolean',
        'requires_disassembly'    => 'boolean',
        'has_fragile_items'       => 'boolean',
        'fine_art_paintings'      => 'boolean',
        'piano_antique_items'     => 'boolean',
        'beds_quantity'           => 'integer',
        'wardrobes_quantity'      => 'integer',
        'custom_access_fields'    => 'array',
        'custom_dismantle_items'  => 'array',
        'custom_fragile_fields'   => 'array',
    ];

    /** The quotations linked to this lead. */
    public function quotations()
    {
        return $this->hasMany(Quotation::class, 'lead_id');
    }

    /** The survey media linked to this lead. */
    public function surveyMedia()
    {
        return $this->hasMany(SurveyMedia::class, 'lead_id');
    }
}
