/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppContactsRouteImport } from './routes/app.contacts'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppJobReschedulesRouteImport } from './routes/app.job-reschedules'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppOutlookRouteImport } from './routes/app.outlook'
import { Route as AppQuotationsRouteImport } from './routes/app.quotations'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSurveyorRouteImport } from './routes/app.surveyor'
import { Route as AppSurveysRouteImport } from './routes/app.surveys'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppJobReschedulesRoute = AppJobReschedulesRouteImport.update({
  id: '/job-reschedules',
  path: '/job-reschedules',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppOutlookRoute = AppOutlookRouteImport.update({
  id: '/outlook',
  path: '/outlook',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveyorRoute = AppSurveyorRouteImport.update({
  id: '/surveyor',
  path: '/surveyor',
  getParentRoute: () => AppRoute,
} as any)
const AppSurveysRoute = AppSurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/chat': typeof AppChatRoute
  '/app/clients': typeof AppClientsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/job-reschedules': typeof AppJobReschedulesRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/outlook': typeof AppOutlookRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/surveyor': typeof AppSurveyorRoute
  '/app/surveys': typeof AppSurveysRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/chat': typeof AppChatRoute
  '/app/clients': typeof AppClientsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/job-reschedules': typeof AppJobReschedulesRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/outlook': typeof AppOutlookRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/surveyor': typeof AppSurveyorRoute
  '/app/surveys': typeof AppSurveysRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/chat': typeof AppChatRoute
  '/app/clients': typeof AppClientsRoute
  '/app/contacts': typeof AppContactsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/job-reschedules': typeof AppJobReschedulesRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/outlook': typeof AppOutlookRoute
  '/app/quotations': typeof AppQuotationsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/surveyor': typeof AppSurveyorRoute
  '/app/surveys': typeof AppSurveysRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/calendar'
    | '/app/chat'
    | '/app/clients'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/integrations'
    | '/app/invoices'
    | '/app/job-reschedules'
    | '/app/jobs'
    | '/app/leads'
    | '/app/outlook'
    | '/app/quotations'
    | '/app/settings'
    | '/app/surveyor'
    | '/app/surveys'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/app/calendar'
    | '/app/chat'
    | '/app/clients'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/integrations'
    | '/app/invoices'
    | '/app/job-reschedules'
    | '/app/jobs'
    | '/app/leads'
    | '/app/outlook'
    | '/app/quotations'
    | '/app/settings'
    | '/app/surveyor'
    | '/app/surveys'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/calendar'
    | '/app/chat'
    | '/app/clients'
    | '/app/contacts'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/integrations'
    | '/app/invoices'
    | '/app/job-reschedules'
    | '/app/jobs'
    | '/app/leads'
    | '/app/outlook'
    | '/app/quotations'
    | '/app/settings'
    | '/app/surveyor'
    | '/app/surveys'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contacts': {
      id: '/app/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/job-reschedules': {
      id: '/app/job-reschedules'
      path: '/job-reschedules'
      fullPath: '/app/job-reschedules'
      preLoaderRoute: typeof AppJobReschedulesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outlook': {
      id: '/app/outlook'
      path: '/outlook'
      fullPath: '/app/outlook'
      preLoaderRoute: typeof AppOutlookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/surveyor': {
      id: '/app/surveyor'
      path: '/surveyor'
      fullPath: '/app/surveyor'
      preLoaderRoute: typeof AppSurveyorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/surveys': {
      id: '/app/surveys'
      path: '/surveys'
      fullPath: '/app/surveys'
      preLoaderRoute: typeof AppSurveysRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppChatRoute: typeof AppChatRoute
  AppClientsRoute: typeof AppClientsRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppJobReschedulesRoute: typeof AppJobReschedulesRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppOutlookRoute: typeof AppOutlookRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSurveyorRoute: typeof AppSurveyorRoute
  AppSurveysRoute: typeof AppSurveysRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppChatRoute: AppChatRoute,
  AppClientsRoute: AppClientsRoute,
  AppContactsRoute: AppContactsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppJobReschedulesRoute: AppJobReschedulesRoute,
  AppJobsRoute: AppJobsRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppOutlookRoute: AppOutlookRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSurveyorRoute: AppSurveyorRoute,
  AppSurveysRoute: AppSurveysRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
